#!/bin/sh

# Configure/install bash and vim 
minimal() {

  if ! command -v bash 2> /dev/null ; then
    echo -e "\033[32;1;4m[*] installing bash\033[0m" 
    sudo apt install bash -y
  fi

  if ! command -v git 2> /dev/null ; then
    echo -e "\033[32;1;4m[*] installing git\033[0m" 
    sudo apt install git -y
  fi

  if ! command -v vim 2> /dev/null ; then
    echo -e "\033[32;1;4m[*] installing vim\033[0m" 
    sudo apt install vim-nox -y
  fi

  if test -f "$HOME/.bashrc"; then
    echo "[*] creating backup folder.."
    echo -e "\033[32;1;4m[*] creating backup folder..\033[0m" 
    mkdir "$HOME/.configuration/backup"
    echo "[bashrc] mv .bashrc backup/bashrc.bak"
    mv "$HOME/.bashrc" "$HOME/.configuration/backup/bashrc.bak"
  fi
  if test -f "$HOME/.vimrc"; then
    echo "[vimrc] mv .vimrc backup/vimrc.bak"
    mv "$HOME/.vimrc" "$HOME/.configuration/backup/vimrc.bak"
  fi

  curl https://raw.githubusercontent.com/76616c6172/config/master/bashrc -o "$HOME/.configuration/bashrc"
  echo "[linking bashrc] .bashrc -> .configuration/bashrc"
  ln -sf "$HOME/.configuration/bashrc" "$HOME/.bashrc"
  curl https://raw.githubusercontent.com/76616c6172/config/master/vimrc -o "$HOME/.configuration/vimrc"
  echo "[linking vimrc] .vimrc -> .configuration/vimrc"
  ln -sf "$HOME/.configuration/vimrc" "$HOME/.vimrc"
}

# call minimal and add tmux
basic() {

	# install bash an vim
  minimal

  if test -f "$HOME/.tmux.conf"; then
    echo "[tmux.conf] mv .tmux.conf backup/tmux.conf.bak"
   mv  "$HOME/.tmux.conf" "$HOME/.configuration/backup/tmux.conf.bak"
  fi

  if ! command -v tmux 2> /dev/null ; then
    echo -e "\033[32;1;4m[*] installing tmux\033[0m" 
    sudo apt install tmux -y
  fi

  curl https://raw.githubusercontent.com/76616c6172/config/master/tmux.conf -o "$HOME/.configuration/tmux.conf"
  echo "[linking tmux.conf] .tmux.conf -> .configuration/tmux.conf"
  ln -sf "$HOME/.configuration/tmux.conf" "$HOME/.tmux.conf"

}

# call minimal and basic and add zsh + git
full() {

  minimal
  basic
  mkdir -p "$HOME/.cache/zsh" && touch "$HOME/.cache/zsh/dirstack"
  mkdir -p "$HOME/.config/nix" && echo "build-users-group = nixbld\nexperimental-features = nix-command flakes" > "$HOME/.config/nix/nix.conf" 


  if ! command -v zsh 2> /dev/null ; then
    echo -e "\033[32;1;4m[*] installing zsh\033[0m" 
  fi
  if ! command -v git 2> /dev/null ; then
    echo -e "\033[32;1;4m[*] installing git\033[0m" 
  fi

  if test -f "$HOME/.zshrc"; then
    echo "[zshrc] mv .zshrc backup/zshrc"
     mv "$HOME/.zshrc" "$HOME/.configuration/backup/zshrc.bak"
  fi

  curl https://raw.githubusercontent.com/76616c6172/config/master/zshrc -o "$HOME/.configuration/zshrc"
  echo "[linking zshrc] .zshrc -> .configuration/zshrc"
  ln -sf "$HOME/.configuration/zshrc" "$HOME/.zshrc"
}

choose_option() {
  echo "[*] CHOOSE OPTION:"
  echo "0: MINIMAL  bash + vim"
  echo "1: BASIC    bash + vim + tmux"
  echo "2: FULL     zsh  + vim + tmux + git"
  read -r x
}

check_option() {
  if test "$x" -eq "0" ; then
  minimal
  chsh -s /bin/bash
  return 0
  fi
  if test "$x" -eq "1" ; then
  basic
  chsh -s /bin/bash
  return 0
  elif test "$x" -eq "2" ; then
  full
  chsh -s /bin/zsh
  return 0
  fi
    echo -e "\033[31;1;4m[!][error] selection must be 0, 1, or 2. Exiting without changes\033[0m" 
  exit 1
}

# execution starts here
mkdir "$HOME/.configuration"
choose_option
check_option
#simple
echo "[*] configuration complete!"
exit 0
